  <script type="test/javascript" src="res/js/bootstrap.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-affix.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-alert.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-button.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-carousel.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-collapse.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-dropdown.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-modal.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-popover.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-scrollspy.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-tab.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-tooltip.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-transition.js"></script>
  <script type="test/javascript" src="res/js/bootstrap-typeahead.js"></script>
